default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rail_blog_app_development
  username: postgres
  password: chua2C@2022

 
test:
  <<: *default
  database: rail_blog_app_test
  username: postgres
  password: chua2C@2022


production:
  <<: *default
  database: rail_blog_app_production
  username: rail_blog_app
  password: <%= ENV['RAIL_BLOG_APP_DATABASE_PASSWORD'] %>
